### ISSUE TITLE
CSV Export - Add "All Autotags" to UnBundled output

### ISSUE THREAD

**Issue by richardkaplan** [kaplanrehab/zotero-seektable-export#1]
See also for reference this discussion on a similar case:

kaplanrehab/zotero-sync-pg#1

**Comment by retorquere** [comment]
Please don't assign issues -- it just generates extra mail notifications, and it's clear I'll be working on this.

**Comment by retorquere** [comment]
It's much better if issues can be read in isolation -- "just like X" is guaranteed to be a cause of confusion given that X may well change in the interim.

**Comment by richardkaplan** [comment]
ok

**Comment by retorquere** [comment]
This is already in 0.0.15 AFAICT?

**Comment by retorquere** [comment]
Wait -- add all_auto_tags to *bundled* output?

**Comment by richardkaplan** [comment]
all_auto-tags only in UNBUNDLED

Thanks

**Comment by retorquere** [comment]
Can you update the issue title and then close it? I think it's in .15
