### ISSUE TITLE
Seektable Export - All Parents Field

### ISSUE THREAD

**Issue by richardkaplan** [kaplanrehab/zotero-seektable-export#2]
We should have an "All Parents" field in CSV Export that works just like the same feature currently in Sync

**Comment by retorquere** [comment]
It's much better if issues can be read in isolation -- "just like X" is guaranteed to be a cause of confusion given that X may well change in the interim. A full description of what you want done in helps getting such things resolved efficiently.

**Comment by retorquere** [comment]
This is already in 0.0.15 AFAICT. If that doesn't do what you wanted from this issue, I'll need more information.

**Comment by richardkaplan** [comment]
yes - found it there in 0.0.15 - thanks

**Comment by retorquere** [comment]
Can you close the issue? I can't.
